# Exercises for TensorFlow fundamentals

**Exercise 1:** Read through TensorFlow documentation on random seed generation:
(https://www.tensorflow.org/api_docs/python/tf/random/set_seed) and practice writing 5 random tensors.

> Rule 4: "If we want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operation level random seed."

In [1]:
import tensorflow as tf

In [110]:
tensor_1 = tf.constant([[[10, 7],
                        [4, 5]],
                       [[2, 8],
                       [1, 9]],
                       [[3, 1],
                       [10, 11]]])
tf.random.shuffle(tensor_1)

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 2,  8],
        [ 1,  9]],

       [[ 3,  1],
        [10, 11]],

       [[10,  7],
        [ 4,  5]]], dtype=int32)>

In [111]:
tf.random.set_seed(1234)
tensor_2 = tf.random.shuffle(tensor_1)
tensor_2

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 3,  1],
        [10, 11]],

       [[10,  7],
        [ 4,  5]],

       [[ 2,  8],
        [ 1,  9]]], dtype=int32)>

In [113]:
tf.random.set_seed(1234)
tensor_3 = tf.random.shuffle(tensor_1, seed=42)
tensor_3

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 4,  5]],

       [[ 3,  1],
        [10, 11]],

       [[ 2,  8],
        [ 1,  9]]], dtype=int32)>

In [116]:
tensor_4 = tf.random.Generator.from_seed(14)
tensor_4 = tensor_4.normal(shape=(3, 2, 2))
tensor_4

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[ 0.8045827 ,  0.4769051 ],
        [-0.7812124 , -0.996891  ]],

       [[ 0.33149973, -0.5445254 ],
        [ 1.5222508 ,  0.59303206]],

       [[-0.63509274,  0.37035653],
        [-1.0939722 , -0.46014452]]], dtype=float32)>

In [117]:
tensor_5 = tf.random.uniform(shape=(3, 2, 2))
tensor_5

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[0.5380393 , 0.36461866],
        [0.5816301 , 0.24382842]],

       [[0.43033564, 0.90619123],
        [0.50722075, 0.35881782]],

       [[0.77884936, 0.5853021 ],
        [0.76881325, 0.48325706]]], dtype=float32)>