# Matrix Multiplication exercises

In [1]:
import tensorflow as tf

In [4]:
# Create two tensor and do the dot product between the two

left = tf.constant([
    [1, 2, 5],
    [7, 2, 1],
    [3, 3, 3]
])

left

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 5],
       [7, 2, 1],
       [3, 3, 3]], dtype=int32)>

In [5]:
right = tf.constant([
    [3, 5],
    [6, 7],
    [1, 8]
])

right

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 8]], dtype=int32)>

In [6]:
tf.matmul(left, right)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>