In [1]:
import tensorflow as tf
tf.__version__

'2.2.0'

# Manipulating tensors (tensor operations)

## Basic Operations
(element-wise operations)
`+`, `-`, `*`, `/`

#### Add values to a tensor using the addition operator

In [3]:
tensor = tf.constant([
    [10, 7],
    [3, 4]
])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [8]:
# We can use tensorflow built-in function to speed up the operation on GPU

tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [4]:
# Original tensor is unchanged, if we want to change it we have to assign it
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

#### Multiplication

In [5]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [7]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

#### Subtraction

In [6]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [9]:
tf.subtract(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

## Matrix Multiplication

In machine learning, matrix multiplication is one of the most common tensor operations.

The "Dot Product" is where we multiply matching members, then sum up

There are two rules our tensors (or matrices) need to fulfil of we're going to matrix multiply them:
1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimension

In [11]:
# Matrix multiplication in TensorFlow

print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [12]:
# Matrix multiplication in Python with "@" operator

tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [2]:
# Create two tensor of the same shape and try to multiply them

X = tf.constant([
    [1, 2],
    [3, 4],
    [5, 6]
])

Y = tf.constant([
    [7, 8],
    [9, 10],
    [11, 12]
])

tf.matmul(X, Y)

InvalidArgumentError: Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

In [14]:
# The inner dimensions are 2 and 3, so they don't match.
# To avoid the error we can reshape Y matrix

tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [15]:
# Try to multiply X for reshaped Y

X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [16]:
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# tf.transpose will give the same shape, but it switch the axis

tf.transpose(Y)