In [1]:
import tensorflow as tf
tf.__version__

'2.2.0'

# Manipulating tensors (tensor operations)

## Basic Operations
(element-wise operations)
`+`, `-`, `*`, `/`

#### Add values to a tensor using the addition operator

In [3]:
tensor = tf.constant([
    [10, 7],
    [3, 4]
])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [8]:
# We can use tensorflow built-in function to speed up the operation on GPU

tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [4]:
# Original tensor is unchanged, if we want to change it we have to assign it
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

#### Multiplication

In [5]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [7]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

#### Subtraction

In [6]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [9]:
tf.subtract(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

## Matrix Multiplication

In machine learning, matrix multiplication is one of the most common tensor operations.

The "Dot Product" is where we multiply matching members, then sum up

There are two rules our tensors (or matrices) need to fulfil of we're going to matrix multiply them:
1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimension

In [11]:
# Matrix multiplication in TensorFlow

print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [12]:
# Matrix multiplication in Python with "@" operator

tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [2]:
# Create two tensor of the same shape and try to multiply them

X = tf.constant([
    [1, 2],
    [3, 4],
    [5, 6]
])

Y = tf.constant([
    [7, 8],
    [9, 10],
    [11, 12]
])

tf.matmul(X, Y)

InvalidArgumentError: Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

In [14]:
# The inner dimensions are 2 and 3, so they don't match.
# To avoid the error we can reshape Y matrix

tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [15]:
# Try to multiply X for reshaped Y

X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [16]:
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [3]:
# tf.transpose will give the same shape, but it switch the axis
# (it switches rows and columns)

tf.transpose(Y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8, 10, 12]], dtype=int32)>

** The Dot product**

Matrix multiplication is also referred to as the dot product.

We can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`

In [ ]:
# Perform the dot product on X and Y (requires X or Y to be transposed)

In [4]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [5]:
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [6]:
# Perform matrix multiplication between X and Y (transposed)

tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [7]:
# Perform matrix multiplication between X and Y (reshaped)

tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [9]:
# Check the values of Y, reshaped Y and transposed Y

print("Normal Y: ")
print(Y, "\n")

print("Y reshaped to (2, 3): ")
print(tf.reshape(Y, (2,3)), "\n")

print("Y transposed: ")
print(tf.transpose(Y))


Normal Y: 
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3): 
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed: 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Generally, when performing matrix multiplication on two tensors and the axes doesn't line up usually one of the tensors get transposed, not reshaped.

## Changing the datatype of a tensor

In [14]:
# Create a new tensor with default datatype (float32 for float tensor, int32 for int)
B = tf.constant([1.7, 7.4])
C = tf.constant([7, 10])
B.dtype, C.dtype

(tf.float32, tf.int32)

In [15]:
# Change from float32 to float16 (reduced precision)

D = tf.cast(B, dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [17]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

## Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [21]:
# Get the absolute values

D = tf.constant([-7, -10])
D, tf.abs(D)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>)

Other forms of aggregation:
* Get the minimum of a tensor
* Get the maximum
* Get the mean
* Get the sum

In [24]:
# Create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([43,  8,  2, 91, 53, 50, 13, 98, 69, 87, 29, 70,  7,  4, 58, 64, 82,
       38, 41, 84, 91, 42, 31, 60, 11, 80, 86, 41, 77, 47, 45, 99, 15, 26,
       27, 35, 44, 36, 24, 42, 96, 51, 65, 39, 19, 29, 93, 90, 75, 63])>

In [25]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [26]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [27]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [28]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=51>

In [29]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2570>

In [32]:
# Find the variance
tf.math.reduce_variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=787>

In [34]:
# Find the standard deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.066349>

## Find the positional maximum and minimum

In [35]:
# Create a new tensor for finding positional minimum and maximum
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.8779557 , 0.9474931 , 0.9041767 , 0.52202487, 0.49482644,
       0.71200335, 0.43088353, 0.37187028, 0.46950388, 0.20541215,
       0.25363743, 0.48225987, 0.31450403, 0.17148352, 0.20853019,
       0.19754517, 0.52795386, 0.8079488 , 0.10374272, 0.42404127,
       0.7504971 , 0.7354722 , 0.8058567 , 0.30756247, 0.99971235,
       0.9801154 , 0.40479326, 0.09921956, 0.7587459 , 0.5769701 ,
       0.47733283, 0.7615539 , 0.9158379 , 0.12459624, 0.62141776,
       0.860463  , 0.4843396 , 0.64543045, 0.30818498, 0.04261756,
       0.0079807 , 0.45824993, 0.4320414 , 0.76633954, 0.23876274,
       0.13670146, 0.27801895, 0.28789425, 0.74888635, 0.36050045],
      dtype=float32)>

In [37]:
# Find the positional maximum
tf.argmax(F), F[24]

(<tf.Tensor: shape=(), dtype=int64, numpy=24>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.99971235>)

In [42]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [41]:
# Find the positional minimum
tf.argmin(F), F[40]

(<tf.Tensor: shape=(), dtype=int64, numpy=40>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.007980704>)

In [44]:
F[tf.argmin(F)] == tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

## Squeezing a tensor (removing all single dimensions)

In [46]:
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[4.2636430e-01, 7.8115797e-01, 6.3533258e-01, 6.0786498e-01,
           6.4588940e-01, 2.7070367e-01, 2.5683999e-02, 1.5121937e-01,
           3.8551056e-01, 7.2993398e-01, 6.2700748e-01, 5.6862354e-02,
           6.8192148e-01, 1.5140390e-01, 4.1595912e-01, 4.9978781e-01,
           5.9748518e-01, 9.4913864e-01, 5.1129520e-01, 6.7411304e-01,
           1.9863880e-01, 6.2713623e-03, 4.3243039e-01, 9.7410679e-01,
           5.3385842e-01, 3.3394098e-03, 8.1898940e-01, 2.2387743e-02,
           9.5039093e-01, 1.6539907e-01, 7.4654806e-01, 8.5534203e-01,
           8.5438716e-01, 6.7647433e-01, 1.7413056e-01, 2.2590160e-04,
           4.6442461e-01, 8.5635960e-01, 5.3176367e-01, 3.1960201e-01,
           7.9738986e-01, 5.7149291e-02, 4.9405968e-01, 4.2127371e-01,
           4.6100402e-01, 7.2587049e-01, 3.6557198e-02, 7.4656868e-01,
           2.5076640e-01, 4.9717247e-01]]]]], dtype=float32)>

In [47]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [48]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([4.2636430e-01, 7.8115797e-01, 6.3533258e-01, 6.0786498e-01,
        6.4588940e-01, 2.7070367e-01, 2.5683999e-02, 1.5121937e-01,
        3.8551056e-01, 7.2993398e-01, 6.2700748e-01, 5.6862354e-02,
        6.8192148e-01, 1.5140390e-01, 4.1595912e-01, 4.9978781e-01,
        5.9748518e-01, 9.4913864e-01, 5.1129520e-01, 6.7411304e-01,
        1.9863880e-01, 6.2713623e-03, 4.3243039e-01, 9.7410679e-01,
        5.3385842e-01, 3.3394098e-03, 8.1898940e-01, 2.2387743e-02,
        9.5039093e-01, 1.6539907e-01, 7.4654806e-01, 8.5534203e-01,
        8.5438716e-01, 6.7647433e-01, 1.7413056e-01, 2.2590160e-04,
        4.6442461e-01, 8.5635960e-01, 5.3176367e-01, 3.1960201e-01,
        7.9738986e-01, 5.7149291e-02, 4.9405968e-01, 4.2127371e-01,
        4.6100402e-01, 7.2587049e-01, 3.6557198e-02, 7.4656868e-01,
        2.5076640e-01, 4.9717247e-01], dtype=float32)>,
 TensorShape([50]))

## One-hot-encoding tensors

In [49]:
# Create a list of indices
some_list = [0, 1, 2, 3] # could be red, green, blue, purple

# One hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [50]:
# Specify custom values for one hot econding
tf.one_hot(some_list, depth=4, on_value="yo I love deep learning", off_value="I also like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deep learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'yo I love deep learning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'yo I love deep learning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'yo I love deep learning']],
      dtype=object)>

## Tensors and NumPy

TensorFlow interacts beautifully with NumPy arrays

In [51]:
# Create a tesnor directly from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [54]:
# Convert the tensor back to a NumPy array
np.array(J), type(np.array(J)), J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray, array([ 3.,  7., 10.]), numpy.ndarray)

In [56]:
# The default types of reach are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

# Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

## Finding access to GPUs

In [59]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:XLA_CPU:0', device_type='XLA_CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'),
 PhysicalDevice(name='/physical_device:XLA_GPU:0', device_type='XLA_GPU')]

In [60]:
!nvidia-smi

Mon Jun 21 12:11:15 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.80       Driver Version: 460.80       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 1050    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   51C    P0    N/A /  N/A |   1842MiB /  2000MiB |     14%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------