# TensorFlow Fundamentals Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape [5, 300].
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
7. Find the min and max values of the tensor you created in 6 along the first axis.
8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.


* Mini Project

Try to create a series of tensor functions to calculate your most recent grocery bill (it's okay if you don't use the names of the items, just the price in numerical form).
    How would you calculate your grocery bill for the month and for the year using tensors?



In [1]:
import tensorflow as tf
tf.__version__

'2.2.0'

#### 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [3]:
scalar = tf.constant(1)
vector = tf.constant([1, 2, 3])
matrix = tf.constant([
    [1, 2],
    [3, 4]
])
tensor = tf.constant([
    [[1, 2],
    [3, 4]],
    
    [[5, 6],
    [7, 8]]
])

#### 2. Find the shape, rank and size of the tensors you created in 1.

In [8]:
# Scalar
print(scalar)
print("Scalar shape: ", scalar.shape)
print("Scalar rank: ", scalar.ndim)
print("Scalar size: ", tf.size(scalar).numpy())

tf.Tensor(1, shape=(), dtype=int32)
Scalar shape:  ()
Scalar rank:  0
Scalar size:  1


In [9]:
# Vector
print(vector)
print("Vector shape: ", vector.shape)
print("Vector rank: ", vector.ndim)
print("Vector size: ", tf.size(vector).numpy())

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Vector shape:  (3,)
Vector rank:  1
Vector size:  3


In [11]:
# Matrix
print(matrix)
print("Matrix shape: ", matrix.shape)
print("Matrix rank: ", matrix.ndim)
print("Matrix size: ", tf.size(matrix).numpy())

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Matrix shape:  (2, 2)
Matrix rank:  2
Matrix size:  4


In [12]:
# Tensor
print(tensor)
print("Tensor shape: ", tensor.shape)
print("Tensor rank: ", tensor.ndim)
print("Tensor size: ", tf.size(tensor).numpy())

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
Tensor shape:  (2, 2, 2)
Tensor rank:  3
Tensor size:  8


#### 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [16]:
random_1 = tf.random.uniform(shape=([5, 300]), minval=0, maxval=1)
random_2 = tf.random.uniform(shape=([5, 300]), minval=0, maxval=1)
random_1.shape, random_2.shape

(TensorShape([5, 300]), TensorShape([5, 300]))

#### 4. Multiply the two tensors you created in 3 using matrix multiplication.


In [20]:
random_1 @ tf.reshape(random_2, shape=[300, 5])

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.684586, 71.13916 , 71.8653  , 74.644516, 75.68515 ],
       [69.35295 , 68.68565 , 67.77207 , 70.39114 , 75.01817 ],
       [73.45467 , 73.80994 , 69.75933 , 73.0615  , 77.98869 ],
       [68.28668 , 61.961266, 67.18791 , 69.59172 , 69.12304 ],
       [70.77962 , 71.039604, 70.54445 , 73.19271 , 78.4776  ]],
      dtype=float32)>

In [21]:
tf.matmul(random_1, tf.reshape(random_2, shape=[300, 5]))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.684586, 71.13916 , 71.8653  , 74.644516, 75.68515 ],
       [69.35295 , 68.68565 , 67.77207 , 70.39114 , 75.01817 ],
       [73.45467 , 73.80994 , 69.75933 , 73.0615  , 77.98869 ],
       [68.28668 , 61.961266, 67.18791 , 69.59172 , 69.12304 ],
       [70.77962 , 71.039604, 70.54445 , 73.19271 , 78.4776  ]],
      dtype=float32)>

In [22]:
tf.matmul(random_1, tf.transpose(random_2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[73.8713  , 75.739746, 77.654625, 69.39139 , 72.76096 ],
       [71.118996, 70.13621 , 73.36661 , 69.081635, 71.0086  ],
       [71.116135, 75.12815 , 76.57327 , 69.84093 , 71.47714 ],
       [67.02683 , 69.82248 , 71.60766 , 65.63347 , 68.05288 ],
       [72.54387 , 75.187904, 78.672424, 70.31302 , 74.34651 ]],
      dtype=float32)>

#### 5. Multiply the two tensors you created in 3 using dot product.


In [25]:
tf.tensordot(random_1, tf.transpose(random_2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[73.8713  , 75.739746, 77.654625, 69.39139 , 72.76096 ],
       [71.118996, 70.13621 , 73.36661 , 69.081635, 71.0086  ],
       [71.116135, 75.12815 , 76.57327 , 69.84093 , 71.47714 ],
       [67.02683 , 69.82248 , 71.60766 , 65.63347 , 68.05288 ],
       [72.54387 , 75.187904, 78.672424, 70.31302 , 74.34651 ]],
      dtype=float32)>

#### 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].


In [26]:
random_3 = tf.random.uniform(shape=[224, 224, 3], minval=0, maxval=1)
random_3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.6562146 , 0.5941645 , 0.02791595],
        [0.85659873, 0.9458524 , 0.35186505],
        [0.05700529, 0.15319812, 0.7709472 ],
        ...,
        [0.7949903 , 0.858232  , 0.03535748],
        [0.9328716 , 0.05912364, 0.8619318 ],
        [0.75264263, 0.4312786 , 0.15648985]],

       [[0.631219  , 0.49585998, 0.9247308 ],
        [0.22505128, 0.873245  , 0.7389413 ],
        [0.8324168 , 0.946591  , 0.8173518 ],
        ...,
        [0.4248669 , 0.24100232, 0.27445173],
        [0.12754083, 0.8641602 , 0.8454665 ],
        [0.22932327, 0.05659378, 0.50905716]],

       [[0.71398413, 0.6257676 , 0.27812183],
        [0.37309134, 0.6041362 , 0.68737674],
        [0.8182639 , 0.82301724, 0.57820857],
        ...,
        [0.91646504, 0.5740942 , 0.28522766],
        [0.96061504, 0.39974678, 0.29977763],
        [0.96515536, 0.14352572, 0.03886664]],

       ...,

       [[0.34375036, 0.81791925, 0.25560713],
        [0.65

#### 7. Find the min and max values of the tensor you created in 6 along the first axis.


In [34]:
# Find the indexes
tf.argmin(random_3, axis=0), tf.argmax(random_3)

(<tf.Tensor: shape=(224, 3), dtype=int64, numpy=
 array([[ 86, 128,  52],
        [ 95,  80, 119],
        [ 62, 171,   7],
        [122, 121, 168],
        [ 95,  91,  29],
        [191,   6,  55],
        [175,  73, 111],
        [ 33, 208,  77],
        [179, 135, 124],
        [ 47,  10, 121],
        [154,  33,  63],
        [ 45,  45,  18],
        [102,   2, 203],
        [117, 180, 204],
        [ 77, 145,  29],
        [216, 113,  22],
        [  0,  97, 183],
        [ 43,  38, 191],
        [ 28,  57, 104],
        [ 68,  97, 203],
        [143,  14, 184],
        [144, 163, 117],
        [ 65,   7, 122],
        [109, 160,  98],
        [187, 203,  37],
        [ 23, 136,  62],
        [177,  32, 161],
        [210,   3, 215],
        [152,  90,  60],
        [199,  22,  26],
        [ 21,  96,  83],
        [205,   6, 198],
        [ 99,  25, 100],
        [116, 141, 209],
        [ 94,  11, 188],
        [115, 151,  59],
        [132, 173, 202],
        [  3,  11,  51],
 

In [35]:
# Find the values
tf.reduce_min(random_3, axis=0), tf.reduce_max(random_3, axis=0)

(<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
 array([[6.58774376e-03, 9.06419754e-03, 1.96933746e-04],
        [6.35337830e-03, 6.14118576e-03, 6.08479977e-03],
        [7.73811340e-03, 4.45950031e-03, 8.03470612e-05],
        [7.20500946e-03, 3.81827354e-04, 3.78978252e-03],
        [1.96194649e-03, 1.22578144e-02, 1.41724348e-02],
        [8.03446770e-03, 1.42145157e-03, 4.83894348e-03],
        [5.57017326e-03, 8.20207596e-03, 2.88450718e-03],
        [2.01690197e-03, 3.96215916e-03, 3.15165520e-03],
        [9.24944878e-03, 3.49688530e-03, 4.77516651e-03],
        [3.14640999e-03, 3.62777710e-03, 1.82238817e-02],
        [1.70612335e-03, 8.69512558e-04, 2.06681490e-02],
        [2.77876854e-03, 5.53607941e-04, 8.22424889e-04],
        [5.75160980e-03, 4.96387482e-03, 9.11784172e-03],
        [1.62339211e-03, 1.69372559e-03, 8.31294060e-03],
        [3.55422497e-03, 5.62167168e-03, 5.31673431e-03],
        [1.39260292e-03, 2.52294540e-03, 4.42969799e-03],
        [1.13403797e-

#### 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].


In [37]:
random_4 = tf.random.uniform(shape=[1, 224, 224, 3])
tf.squeeze(random_4).shape

TensorShape([224, 224, 3])

#### 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [40]:
my_tensor = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_tensor.shape, tf.argmax(my_tensor).numpy()

(TensorShape([10]), 9)

#### 10. One-hot encode the tensor you created in 9.


In [43]:
tf.one_hot(my_tensor, depth=9)

<tf.Tensor: shape=(10, 9), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>